# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyler_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=400)),
                ('logo', models.ImageField(upload_to='images/logos')),
                ('testimonial', models.TextField()),
            ],
        ),
    ]
