# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyler_site', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(default='Developer', max_length=200),
            preserve_default=False,
        ),
    ]
