# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyler_site', '0003_testimonial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Callum Pullinger', max_length=200),
            preserve_default=False,
        ),
    ]
