# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyler_site', '0007_auto_20181021_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=14)),
                ('booking_time', models.TimeField(choices=[(datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 PM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM')], verbose_name='Booking time')),
                ('day', models.DateField(verbose_name='Booking date')),
            ],
        ),
    ]
