# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyler_site', '0009_callbooking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbooking',
            name='booking_time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9 AM'), (datetime.time(10, 0), '10 AM'), (datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 PM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM')], verbose_name='Booking time'),
        ),
    ]
