# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyler_site', '0010_auto_20181021_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='service',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Not required', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Not required', null=True, upload_to='images'),
        ),
    ]
